package citas;

public class CitaActiva {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cita_activa.CitaID
     *
     * @mbg.generated Fri Nov 16 12:33:10 CET 2018
     */
    private Integer citaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cita_activa.CitaID
     *
     * @return the value of cita_activa.CitaID
     *
     * @mbg.generated Fri Nov 16 12:33:10 CET 2018
     */
    public Integer getCitaid() {
        return citaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cita_activa.CitaID
     *
     * @param citaid the value for cita_activa.CitaID
     *
     * @mbg.generated Fri Nov 16 12:33:10 CET 2018
     */
    public void setCitaid(Integer citaid) {
        this.citaid = citaid;
    }
}